// Ghost suggestions for the empty line: scenes and feelings, never bare mood words. Some are short,
// casual, and first person, to show that a feeling does not need to be written perfectly.

export const EXAMPLES = [
	'a snowy december and i just made warm hot chocolate',
	'rain on the window and nowhere to be',
	'i just want to feel cozy',
	'driving home at 2am with the windows down',
	'i miss summer so much',
	'the last day of summer, sunburnt and a little sad',
	'a library so quiet you can hear the pages turn',
	'i feel like the main character today',
	'neon puddles outside a ramen bar after midnight',
	'golden light through the kitchen window while the bread rises',
	'a night train through the mountains and i am the only one awake',
	'the first cold morning and the smell of somebody else’s fireplace',
	'dancing alone in the kitchen to a song i had forgotten',
	'honestly i’m just tired and want something soft',
	'an empty beach in february, grey water and a long coat',
	'the city from a rooftop just before the storm breaks',
	'a slow sunday with the record player and nothing planned',
	'i finished my last exam and i’m free',
	'walking home from a party, still humming, streetlights buzzing',
	'my grandmother’s house smells of cardamom and floor polish',
	'the fluorescent hum of a laundromat at eleven on a tuesday',
	'first day of school, new shoes, and a stomach full of bees',
	'fog so thick the lighthouse is only a sound',
	'we missed the last bus and walked the whole way laughing',
	'a heatwave in the city and every window open',
	'i can’t sleep and my brain won’t stop',
	'the power went out and we played cards by candlelight',
	'cherry blossoms falling on a canal in the rain',
	'the office after everyone has gone home, just the copier breathing',
	'i got the job and i do not know who to tell first',
	'the long bus ride back from the funeral, everyone quiet',
	'a street market in marrakech, spices and shouting and brass',
	'my little brother asleep in the back seat on a road trip',
	'the pool at a cheap motel, lit up blue at night',
	'the smell of wet asphalt after the first summer storm',
	'moving out of the flat where i lived for ten years',
	'three in the morning, a fever, and the ceiling fan turning',
	'a wedding in a village square with too many lanterns',
	'ice skating on a frozen pond while the sun goes down',
	'a text from an old friend i thought had forgotten me',
	'the waiting room of a dentist with a fish tank and no magazines',
	'cycling to the sea with bread in the basket',
	'the kettle clicks off and the house is finally quiet',
	'a thunderstorm over the prairie and we watch from the porch',
	'lost in tokyo at rush hour and somehow happy about it',
	'the last night of a festival, mud to the knees, lights everywhere',
	'a dusty attic full of letters from people i never met',
	'autumn leaves in a park and a coffee too hot to drink',
	'the hour after a big argument, both of us pretending to read',
	'a carnival at the edge of town that feels a little haunted',
	'watching my dad fix the car and handing him the wrong tools',
	'a monsoon afternoon, chai on the balcony, the street a river',
	'the train pulls in and there you are on the platform',
	'an abandoned mall with one fountain still running',
	'reading under the covers with a flashlight long after bedtime',
	'the ferry across the bay with salt in my hair',
	'christmas eve and the house is loud and full of family',
	'a quiet diner at dawn, pie in a glass case, radio low',
	'the snow has stopped and the whole street is holding its breath',
	'bored in a classroom watching the clock that never moves',
	'a jazz bar in a basement, low light and a slow saxophone',
	'an orchard in late september, wasps drunk on fallen pears',
	'the moment the plane lifts off and the city tilts away',
	'my first apartment, one chair, a mattress, and so much hope',
	'a long walk in the desert where the stars come down low',
	'grandpa’s workshop, sawdust and an old radio',
	'the day after a breakup and the sun has the nerve to shine',
	'a lake at midsummer and the sky never gets dark',
	'the school dance, the slow song, and nobody dares to move',
	'a boat of lanterns drifting down the river at night',
	'the bakery at five in the morning before the doors open',
	'a video call with my mum across nine time zones',
	'hiding from the rain under an awning with a stranger',
	'the empty stadium after the match, rubbish blowing like snow',
	'a cabin in the woods and the fire is the only clock',
	'we ate mangoes on the roof until our hands were sticky',
	'the museum closes in ten minutes and i am alone with the paintings',
	'a new city, a new language, and i ordered the wrong thing again',
	'a hammock between two palms and absolutely nothing to do',
	'the dog is getting old and still waits for me at the door',
	'a karaoke room at 4am, voices gone, still singing',
	'a winter market with mulled wine and fingers too cold to count coins',
	'the lab at night, a centrifuge whirring, coffee going cold',
	'the first swim of the year and the water is a shock',
	'i’m homesick for a place i can’t go back to',
	'sitting on the stairs at a party, talking to someone about everything',
	'a greenhouse in january, warm glass and tomato leaves',
	'the hush of a church in the afternoon when no one is there',
	'the wind before a hurricane and the shutters banging'
];
